# Generated by Django 3.1.5 on 2021-01-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=10)),
                ('district', models.CharField(blank=True, max_length=10)),
                ('location_x', models.IntegerField(blank=True)),
                ('location_y', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food')], max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('rating', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
